name: DÃ©ploiement Automatique (Prod)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: ðŸš€ Deploy to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¥ RÃ©cupÃ©ration du code (Checkout)
      uses: actions/checkout@v3

    - name: ðŸšš Transfert des fichiers (SCP)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "."
        target: "/var/www/eidia-absences.com/public_html/"
        rm: true # Cleans the folder before upload to avoid conflicts
