name: DÃ©ploiement Automatique (Prod)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: ðŸš€ Deploy to Google Cloud (Debian)
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¥ RÃ©cupÃ©ration du code
      uses: actions/checkout@v4

    - name: ðŸšš Transfert SCP
      uses: appleboy/scp-action@master
      with:
        # Configuration de connexion (via Secrets GitHub)
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        
        # Dossiers
        source: "."
        target: "/var/www/eidia-absences.com/public_html/"
        
        # Options de nettoyage (Supprime l'ancien code avant de mettre le nouveau)
        rm: false
